Repository RestartDK/ie-bank, pull requests merged in 2024-11, with the labels that each got.

#11 build: added dependabot.yml
  .github/dependabot.yml
Labels: dependencies

#13 Added the Github-pages Doc
  docs/CloudArchitect.md
  docs/Cybersecurity.md
  docs/Fullstack.md
  docs/Infra.md
  docs/PO.md
  docs/Sitereliable.md
  docs/index.md
Labels: documentation

#14 feat: added docker builds
  backend/.dockerignore
  backend/Dockerfile
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
Labels: enhancement

#15 Modularisation
  backend/.dockerignore
  backend/Dockerfile
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
  infra/main.bicep
  infra/modules/app-service-be.bicep
  infra/modules/app-service-fe.bicep
  infra/modules/app-service-plan.bicep
  infra/modules/app-service.bicep
  infra/modules/postgre-sql-db.bicep
  infra/modules/postgre-sql-server.bicep
Labels: enhancement

#16 Docker registry
  bicepconfig.json
  infra/main.bicep
  infra/modules/app-service-be.bicep
  infra/modules/app-service-plan.bicep
  infra/modules/container-registry.bicep
  infra/parameters/dev.parameters.json
Labels: enhancement

#18 feat: app-insights and azure log
  infra/main.bicep
  infra/modules/app-insights.bicep
  infra/modules/app-service-fe.bicep
  infra/modules/azure-log-analytics.bicep
  infra/parameters/dev.parameters.json
  infra/parameters/uat.parameters.json
Labels: enhancement

#19 Feat/app insights
  infra/main.bicep
  infra/modules/app-insights.bicep
  infra/modules/app-service-be.bicep
  infra/modules/app-service-fe.bicep
  infra/parameters/prod.parameters.json
Labels: enhancement
